### ISSUE TITLE
Display matomat ist dunkel

### ISSUE THREAD

**Issue by uescher** [shackspace/spaceIssues#7]
Das Display zeigt nichts mehr an.
Software / Hardware defekt?
Who know it?

**Comment by armageddon421** [comment]
Display ist nicht mehr dunkel. Allerdings ist die Funktionalität nicht mit umgezogen worden, als damals die Pollin-Box durch einen raspi ersetzt wurde. Die Anzeige ist daher momentan nicht dynamisch.
